// components/language-chooser/react/language-chooser-react-daisyui/src/lib/LanguageChooser.tsx
import React, { useRef } from "react";
import {
  createTagFromOrthography,
  type IOrthography,
} from "@ethnolib/find-language";
import { useField } from "@ethnolib/state-management-react";
import { useLanguageChooserViewModel, type LanguageCardViewModel, type ScriptCardViewModel } from "@ethnolib/language-chooser-controller";
import { LanguageCard } from "./LanguageCard";
import { ScriptCard } from "./ScriptCard";
import { SearchIcon } from "./SearchIcon";
import { CustomizationModal } from "./CustomizationModal";

interface LanguageListItemProps {
  lang: LanguageCardViewModel;
  listedScripts: ScriptCardViewModel[];
  onLanguageSelected: (element: HTMLElement) => void;
}

const LanguageListItem: React.FC<LanguageListItemProps> = ({
  lang,
  listedScripts,
  onLanguageSelected,
}) => {
  const [isSelected] = useField(lang.isSelected);

  return (
    <>
      <LanguageCard viewModel={lang} onSelect={onLanguageSelected} />
      {isSelected && listedScripts.length > 0 && (
        <div className="ml-8 mb-4">
          <div className="py-2">
            <p className="font-semibold text-sm">Select a script:</p>
          </div>
          <div className="grid grid-cols-3 gap-4">
            {listedScripts.map((script, scriptIndex) => (
              <ScriptCard key={scriptIndex} viewModel={script} />
            ))}
          </div>
        </div>
      )}
    </>
  );
};

interface LanguageChooserProps {
  onDismiss: () => void;
  onOk: (orthography: IOrthography, languageTag?: string) => void;
}

export const LanguageChooser: React.FC<LanguageChooserProps> = ({
  onDismiss,
  onOk,
}) => {
  const viewModel = useLanguageChooserViewModel();
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  const [searchString, setSearchString] = useField(viewModel.searchString);
  const [displayName, setDisplayName] = useField(viewModel.displayName);
  const [listedLanguages] = useField(viewModel.listedLanguages);
  const [listedScripts] = useField(viewModel.listedScripts);
  const [selectedLanguage] = useField(viewModel.selectedLanguage);
  const [selectedScript] = useField(viewModel.selectedScript);
  const [customizations] = useField(viewModel.customizations);
  const [customLanguageTag] = useField(viewModel.customLanguageTag);
  const [tagPreview] = useField(viewModel.tagPreview);
  const [isReadyToSubmit] = useField(viewModel.isReadyToSubmit);

  const orthography: IOrthography = {
    language: selectedLanguage,
    script: selectedScript,
    customDetails: customizations,
  };

  const languageTag = createTagFromOrthography(orthography);

  const scrollToSelectedCard = (cardElement: HTMLElement) => {
    if (!scrollContainerRef.current || !cardElement) return;

    const containerRect = scrollContainerRef.current.getBoundingClientRect();
    const cardRect = cardElement.getBoundingClientRect();

    const scrollTop =
      scrollContainerRef.current.scrollTop + (cardRect.top - containerRect.top);

    scrollContainerRef.current.scrollTo({
      top: scrollTop,
      behavior: "smooth",
    });
  };

  const onLanguageSelected = (cardElement: HTMLElement) => {
    // Allow scripts to appear or disappear before scrolling
    setTimeout(() => scrollToSelectedCard(cardElement), 0);
  };

  return (
    <div className="h-full flex flex-col">
      <h3 className="text-3xl p-4 border-b-2 border-base-300 flex-none">
        Choose Language
      </h3>

      <div className="flex flex-1 min-h-0">
        <div className="flex-1 flex flex-col min-h-0 bg-base-200 p-4">
          <div className="flex-none pb-1">
            <label className="input w-full">
              <SearchIcon />
              <input
                type="search"
                placeholder="Search by name, code, or country"
                value={searchString}
                onChange={(e) => setSearchString(e.target.value)}
              />
            </label>
          </div>

          <div
            className="flex-1 overflow-y-auto min-h-0"
            ref={scrollContainerRef}
          >
            {listedLanguages.slice(0, 100).map((lang, index) => (
              <LanguageListItem
                key={index}
                lang={lang}
                listedScripts={listedScripts}
                onLanguageSelected={onLanguageSelected}
              />
            ))}
          </div>

          <div className="flex-none py-2">
            <div className="card card-xs card-border border-base-300 bg-base-100 hover:bg-base-300 shadow-xl w-48 px-2">
              <button
                className="card-body text-left"
                onClick={() => viewModel.onCustomizeButtonClicked()}
              >
                <p className="card-title uppercase">
                  {customLanguageTag
                    ? "Edit Language Tag"
                    : selectedLanguage
                    ? "Customize"
                    : "Unlisted Language"}
                </p>
                <div className="flex">
                  <p className="flex-1 font-mono text-sm opacity-60">
                    {tagPreview}
                  </p>
                </div>
              </button>
            </div>
          </div>
        </div>

        <div className="flex-1 flex flex-col p-6">
          <div className="flex-1"></div>
          <div className="flex-none">
            {selectedLanguage && (
              <>
                <label>
                  <span className="font-semibold opacity-70">
                    Display this language this way
                  </span>
                  <input
                    className="input input-xl w-full"
                    value={displayName}
                    onChange={(e) => setDisplayName(e.target.value)}
                  />
                </label>
                <div className="font-mono opacity-70 p-2">
                  <p>{tagPreview}</p>
                </div>
              </>
            )}
            <div className="flex justify-end">
              <button
                className="btn btn-primary uppercase w-24 mx-1"
                disabled={!isReadyToSubmit}
                onClick={() => onOk(orthography, languageTag)}
              >
                Ok
              </button>
              <button className="btn uppercase w-24 mx-1" onClick={onDismiss}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>

      <CustomizationModal
        languageChooser={viewModel}
        onClose={() => {
          /* No action needed on close */
        }}
      />
    </div>
  );
};

// components/language-chooser/svelte/language-chooser-svelte-daisyui/src/lib/LanguageChooser.svelte
<script lang="ts">
  import {
    createTagFromOrthography,
    isValidBcp47Tag,
    type IOrthography,
  } from "@ethnolib/find-language";
  import LanguageCard from "./LanguageCard.svelte";
  import ScriptCard from "./ScriptCard.svelte";
  import SearchIcon from "./SearchIcon.svelte";
  import { useLanguageChooserViewModel } from "@ethnolib/language-chooser-controller";
  import { svelteViewModel } from "@ethnolib/state-management-svelte";
  import CustomizationModal from "./CustomizationModal.svelte";
  import { tick } from "svelte";
  import { t } from "svelte-i18n-lingui";

  const {
    onDismiss,
    onOk,
  }: {
    onDismiss: () => void;
    onOk: (orthography: IOrthography, languageTag?: string) => void;
  } = $props();

  const viewModel = svelteViewModel(useLanguageChooserViewModel());

  let orthography: IOrthography = $derived({
    language: viewModel.selectedLanguage,
    script: viewModel.selectedScript,
    customDetails: viewModel.customizations,
  });

  let languageTag = $derived(createTagFromOrthography(orthography));

  let closeModal = $state(() => {});
  let scrollContainer: HTMLElement;

  viewModel.promptForCustomTag = (_default?: string) => {
    const tag = window.prompt(
      $t`If this user interface is not offering you a language tag that you know is valid ISO 639 code, you can enter it here:`,
      _default
    );
    if (tag && !isValidBcp47Tag(tag)) {
      alert($t`This is not in a valid IETF BCP 47 format: ${tag}`);
    } else if (tag) {
      viewModel.customLanguageTag = tag;
      closeModal();
    }
  };

  async function onLanguageSelected(cardElement: HTMLElement) {
    // Allow scripts to appear or disappear before scrolling
    await tick();
    scrollToSelectedCard(cardElement);
  }

  async function scrollToSelectedCard(cardElement: HTMLElement) {
    if (!scrollContainer || !cardElement) return;

    // Get the position of the card relative to the scroll container
    const containerRect = scrollContainer.getBoundingClientRect();
    const cardRect = cardElement.getBoundingClientRect();

    // Calculate the scroll position needed to bring the card to the top
    const scrollTop =
      scrollContainer.scrollTop + (cardRect.top - containerRect.top);

    scrollContainer.scrollTo({
      top: scrollTop,
      behavior: "smooth",
    });
  }
</script>

<div class="h-full flex flex-col">
  <h3 class="text-3xl p-4 border-b-2 border-base-300 flex-none">
    {$t`Choose Language`}
  </h3>

  <div class="flex flex-1 min-h-0">
    <div class="flex-1 flex flex-col min-h-0 bg-base-200 p-4">
      <div class="flex-none pb-1">
        <label class="input w-full">
          <SearchIcon />
          <input
            type="search"
            placeholder={$t`Search by name, code, or country`}
            bind:value={viewModel.searchString}
          />
        </label>
      </div>

      <div class="flex-1 overflow-y-auto min-h-0" bind:this={scrollContainer}>
        {#each viewModel.listedLanguages
          .slice(0, 100)
          .map(svelteViewModel) as lang}
          <LanguageCard viewModel={lang} onSelect={onLanguageSelected} />
          {#if lang.isSelected && viewModel.listedScripts.length > 0}
            <div class="ml-8 mb-4">
              <div class="py-2">
                <p class="font-semibold text-sm">{$t`Select a script`}:</p>
              </div>
              <div class="grid grid-cols-3 gap-4">
                {#each viewModel.listedScripts.map(svelteViewModel) as script}
                  <ScriptCard viewModel={script} />
                {/each}
              </div>
            </div>
          {/if}
        {/each}
      </div>

      <div class="flex-none py-2">
        <div
          class="card card-xs card-border border-base-300 bg-base-100 hover:bg-base-300 shadow-xl w-48 px-2"
        >
          <button
            class="card-body text-left"
            onclick={() => viewModel.onCustomizeButtonClicked()}
          >
            <p class="card-title uppercase">
              {#if viewModel.customLanguageTag}
                {$t`Edit Language Tag`}
              {:else if viewModel.selectedLanguage}
                {$t`Customize`}
              {:else}
                {$t`Create Unlisted Language`}
              {/if}
            </p>
            <div class="flex">
              <p class="flex-1 font-mono text-sm opacity-60">
                {viewModel.tagPreview}
              </p>
            </div>
          </button>
        </div>
      </div>
    </div>

    <div class="flex-1 flex flex-col p-6">
      <div class="flex-1"></div>
      <div class="flex-none">
        {#if viewModel.selectedLanguage}
          <label>
            <span class="font-semibold opacity-70"
              >{$t`Display this language this way`}</span
            >
            <input
              class="input input-xl w-full"
              bind:value={viewModel.displayName}
            />
          </label>
          <div class="font-mono opacity-70 p-2">
            <p>{viewModel.tagPreview}</p>
          </div>
        {/if}
        <div class="flex justify-end">
          <button
            class="btn btn-primary uppercase w-24 mx-1"
            disabled={!viewModel.isReadyToSubmit}
            onclick={() => onOk(orthography, languageTag)}>{$t`OK`}</button
          >
          <button class="btn uppercase w-24 mx-1" onclick={onDismiss}
            >{$t`Cancel`}</button
          >
        </div>
      </div>
    </div>
  </div>
</div>

<CustomizationModal languageChooser={viewModel} bind:closeModal />
