// components/language-chooser/svelte/language-chooser-svelte-daisyui/src/lib/UnlistedLanguageForm.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import { getAllRegions, type IRegion } from "@ethnolib/find-language";

  let {
    populate = $bindable(),
    onSubmitClicked = $bindable(),
    submit,
  }: {
    populate: (fields: { name?: string; region?: IRegion }) => void;
    onSubmitClicked: () => void;
    submit: (name: string, region: IRegion) => void;
  } = $props();

  const regions = getAllRegions().sort((a, b) => a.name.localeCompare(b.name));

  let name = $state("");
  let regionCode = $state("");

  let showErrors = $state(false);
  let isNameInvalid = $derived(showErrors && !name);
  let isRegionInvalid = $derived(showErrors && !regionCode);

  populate = (fields) => {
    name = fields.name ?? "";
    regionCode = fields.region?.code ?? "";
    showErrors = false;
  };

  onSubmitClicked = () => {
    showErrors = true;
    const region = regions.find((r) => r.code === regionCode);
    if (name && region) {
      submit(name, region);
    }
  };
</script>

<div class="card card-border border-info text-sm mb-4 p-4">
  {$_("If you cannot find a language and it does not appear in ethnologue.com, you can instead define the language here.")}
</div>

<div class="mb-4">
  <label>
    <span class="font-semibold opacity-70">{$_("Name")}</span>
    <input
      class="input w-full"
      class:input-error={isNameInvalid}
      bind:value={name}
    />
    {#if isNameInvalid}
      <p class="text-sm text-error">{$_("required")}</p>
    {/if}
  </label>
</div>

<div class="mb-4">
  <label>
    <span class="font-semibold opacity-70">{$_("Country")}</span>
    <select
      class="select w-full"
      class:select-error={isRegionInvalid}
      bind:value={regionCode}
    >
      <option disabled selected value="">{$_("Select a country")}</option>
      {#each regions as region}
        <option value={region.code}>{region.name}</option>
      {/each}
    </select>
    {#if isRegionInvalid}
      <p class="text-sm text-error">{$_("required")}</p>
    {/if}
  </label>
</div>

// components/language-chooser/react/language-chooser-react-daisyui/src/lib/UnlistedLanguageForm.tsx
import { useState, useImperativeHandle, forwardRef } from "react";
import { getAllRegions, type IRegion } from "@ethnolib/find-language";

interface UnlistedLanguageFormProps {
  submit: (name: string, region: IRegion) => void;
}

export interface UnlistedLanguageFormHandle {
  populate: (fields: { name?: string; region?: IRegion }) => void;
  onSubmitClicked: () => void;
}

export const UnlistedLanguageForm = forwardRef<
  UnlistedLanguageFormHandle,
  UnlistedLanguageFormProps
>(function UnlistedLanguageForm({ submit }, ref) {
  const [name, setName] = useState("");
  const [regionCode, setRegionCode] = useState("");
  const [showErrors, setShowErrors] = useState(false);
  const regions = getAllRegions().sort((a, b) => a.name.localeCompare(b.name));

  useImperativeHandle(ref, () => ({
    populate: (fields: { name?: string; region?: IRegion }) => {
      setName(fields.name ?? "");
      setRegionCode(fields.region?.code ?? "");
      setShowErrors(false);
    },
    onSubmitClicked: () => {
      setShowErrors(true);
      const region = regions.find((r) => r.code === regionCode);
      if (name && region) {
        submit(name, region);
      }
    },
  }));

  const isNameInvalid = showErrors && !name;
  const isRegionInvalid = showErrors && !regionCode;

  return (
    <>
      <div className="card card-border border-info text-sm mb-4 p-4">
        If you cannot find a language and it does not appear in ethnologue.com,
        you can instead define the language here.
      </div>

      <div className="mb-4">
        <label>
          <span className="font-semibold opacity-70">Name</span>
          <input
            className={`input w-full ${isNameInvalid ? "input-error" : ""}`}
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          {isNameInvalid && <p className="text-sm text-error">Required</p>}
        </label>
      </div>

      <div className="mb-4">
        <label>
          <span className="font-semibold opacity-70">Country</span>
          <select
            className={`select w-full ${isRegionInvalid ? "select-error" : ""}`}
            value={regionCode}
            onChange={(e) => setRegionCode(e.target.value)}
          >
            <option disabled value="">
              Select a country
            </option>
            {regions.map((region) => (
              <option key={region.code} value={region.code}>
                {region.name}
              </option>
            ))}
          </select>
          {isRegionInvalid && <p className="text-sm text-error">Required</p>}
        </label>
      </div>
    </>
  );
});
